<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Initial migration: creates receipt, api_key, and messenger_messages tables.
 *
 * If you have an existing database created via doctrine:schema:create,
 * mark this migration as already executed:
 *
 *   php bin/console doctrine:migrations:version --add --all
 */
final class Version20260810185103 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create initial database schema (receipt, api_key, messenger_messages).';
    }

    public function up(Schema $schema): void
    {
        // Schema generated by doctrine:migrations:diff from entity metadata
        $this->addSql('CREATE TABLE api_key (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, key_hash VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE receipt (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, amount NUMERIC(10, 2) NOT NULL, location VARCHAR(255) DEFAULT NULL, business VARCHAR(255) NOT NULL, category VARCHAR(100) NOT NULL, tags CLOB DEFAULT NULL, notes CLOB DEFAULT NULL, raw_input CLOB DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)');
        $this->addSql('CREATE TABLE messenger_messages (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, body CLOB NOT NULL, headers CLOB NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL)');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // Revert schema to empty state
        $this->addSql('DROP TABLE api_key');
        $this->addSql('DROP TABLE receipt');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
